services:
  - type: web
    name: senior-project-backend
    env: docker
    repo: https://github.com/Boost-Oat-SeniorProject/SeniorProjectBackend.git
    branch: main
    plan: free
    region: oregon
